player:
  status:
    manage:
      enter: You have entered Shop Management mode.
      exit: You have left Shop Management mode.
      error: To change your Management status pass "true" or "false".
price: Price
shops:
  list:
    noshops: You don't currently own any shops.
    yourshops: 'Your current shops:'
conversation:
  setsellprice:
    prefix: SET SELL PRICE
    setprice: What would you like to charge for {0}?
  error:
    notadouble: Value needs to be a number value (2, 12.12)