name: UltraTrader
main: com.thedemgel.ultratrader.UltraTrader
version: .11 BETA
depend: [Vault]
softdepend: [Citizens]

commands:
   trader:
      description: This is a demo command.
      usage: /<command> [player]
      permission-message: You don't have <permission>
   traderadmin:
      description: Utility commands I will remove later
      usage: /<command> [subcommand]
