name: CitiTraderRE
main: com.thedemgel.cititradersre.CitiTrader
version: 1
depend: [Vault]
softdepend: [Citizens]

commands:
   trader:
      description: This is a demo command.
      usage: /<command> [player]
      permission-message: You don't have <permission>
   util:
      description: Utility commands I will remove later
      usage: /<command> [subcommand]
